server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: ishopping-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hhy940670358/ishopping-config.git
          username: hhy940670358
          password: hehuiyang940670358
